#!/bin/bash
name="$0"
name=$(echo $name | cut -c 3-)

if grep -q $name .gitignore
then
	true
else
	echo $name>>.gitignore
fi

message=$1
if [$1 -eq ""]
then
	message="empty commit message"
fi

git add .
git commit -m "$message"
git push
